### ISSUE TITLE
Persistent data 

### ISSUE THREAD

**Issue by squest** [Gozala/wisp#116]
I wonder, whether we can use mori by default to provide immutable data structure. That would be one step closer to clojure.

**Comment by kolya-ay** [comment]
`mori` seems to be just a [cljurescript code extractor](https://github.com/swannodette/mori/blob/master/src/bonsai/core.cljs#L8-L37) though. I think it's strange to use clojurescript parts in such little nice language;)
However it would be cool to have an option in wisp compiler to use facebook's `immutable-js` collections instead of native. As it's API [looks really Javascript first](https://github.com/facebook/immutable-js#javascript-first-api) it might be reasonable doable

**Comment by squest** [comment]
Ah, yes I misperceived the intend of the language then :) 
That immutable-js looks interesting, I'll play around with that, thanks for the suggestion.
