### ISSUE TITLE
dash to camelcase not working as expected for object keys

### ISSUE THREAD

**Issue by vshesh** [Gozala/wisp#137]
If I write a function like 

```clojure
(defn f [x] x.y-z)
```
it will compile to 
```js
var f = function f(x) {return x.yZ}
```

However, if I try to call this function with 
```clojure
(f {:y-z 1})
```
That compiles to 
```js
f({"y-z": 1})
```
which is obviously not symmetrical, and returns `undefined` instead of `1`.

I'm curious as to whether this behavior is expected, and if so, why, or whether this is unintended (and if so, how we might fix it). It's just strange to have to have pass `f({:yZ 1})` to a function that uses `:y-z` instead.

**Comment by robjens** [comment]
Yes the behavior is conformant to how wisp is current designed. There is no symbolic translation from and to arbitrary key names of potentially infinitely deep objects. This would usually boil down to either a runtime overhead (having to translate just-in-time) or much additional compile time since not only the structures themselves would need to be translated (e.g. the hardcoded `(def bar {:foo? (fn [] {:bar! {:baz {:bal+bak [1 2 3]}}})})` to e.g. `var bar = {isFoo: function() { return {barExclamation: {baz: {balPlusBak: [1, 2, 3]}}}}` but also the functions/structures referencing them `(def foo? (:foo? bar))` would need to equal `var isFoo = {isFoo: bar};`.

Imho it is too big of a price to pay, where most users of wisp will likely have wisp modules reference wisp modules and the generated code just works. The JS will normally use either a single monolythic access function (e.g. `module.exports = (function [x] ... )`) or resort to functions for their needs and JSON for their object/data storage.

"It is better to have 100 functions operate on one data structure than 10 functions on 10 data structures." —Alan Perlis

So to answer: it is not only `-` dashes to `_` underscores. There would be a whole lot more to it:
`*earmuffs*`, `mutability!`, `predicate?`, `arrows->` and so forth. And to be fair, currently symbol reading/writing is a pile of mutative mess (go an have a look) which really can't deal with much more complexity on this front I think without a full rewrite of the writer.

I've been wondering if `immutable.js` would be an outcome here (and for destructuring). It's also available for both Node and browser (as browserify).

**Comment by vshesh** [comment]
Ok, that makes sense. 
I suppose the correct thing to do is use `(get x :y-z")` which is the correct clojure way to access an element anyway. the `.` syntax is supposed to be for interop, so I understand why this makes sense.
Thanks for the explanation!
