### ISSUE TITLE
func and func! compile to the same name

### ISSUE THREAD

**Issue by noffle** [Gozala/wisp#146]
This might be avoided by mapping `!` -> `BANG`, which is a relatively uncommon suffix. This would allow programs like

```clojure
(defn inc [x] (+ 1 x))

(defn inc! [x] (set! x (inc x)))
```

```js
var inc = exports.inc = function (x) { return 1 + x }

var incBANG = exports.incBANG = function (x) { x = inc(x) }
```

**Comment by Gozala** [comment]
It was intentional, idea was to have a convention of referring to functions that perform mutations with `!` prefix regardless if they were from JS or wisp. It was also making JS interop nicer as calling `incBANG` from JS would be awkward.

That being said this project is abandoned (see https://github.com/gozala/wisp#project-is-abandoned) so unsell someone takes ownership of it there's no point in issue reports.

**Comment by noffle** [comment]
I'm contemplating doing some work on it. Is me filing issues here causing noise for you? I can track them on my fork if you'd prefer.

**Comment by Gozala** [comment]
@noffle no I don't mind that, I just wanted to make sure you were aware of the current status.

**Comment by noffle** [comment]
Thanks for the heads-up and for not minding -- appreciated.
